#!/usr/bin/env bash

echo > test_output

for file in $(find chapters -name "test*.go"); do
  expected=${file/.go/.expected}
  if [ -f $expected ]; then
		if diff <( go run $file) $expected > /dev/null; then
			echo -n .
		else
			echo "Failed: $file" >> test_output
			echo "  To reset, run:" >> test_output
			echo "  rm $expected" >> test_output
			diff -y <( go run $file) $expected >> test_output
			echo >> test_output
			echo -n x
		fi
  else
		echo
    echo "$expected not found - generating it..."
    go run $file > $expected
  fi
done
echo
cat test_output
